receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:

exporters:
  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label: value

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [zipkin, logging]
      processors: [batch]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]